{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v157.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.1.jar",
          "url": "backend-robovm-v157.1.jar",
          "size": 80635,
          "sha512": "d268a5bcafa9e8de80b6ca6a5937d60567dda989fd3d84a42d469c1a6e6cd3c190c6359f45d636066a1f5d8a8c76d95a2ee24dd7ad4b70958ddcc52223fec10b",
          "sha256": "6725bdcef0bc4605e0119377d143413fa4b05d7b16d9fbf61c36a4781f8735d4",
          "sha1": "25a5671eb00ff56dfc04b6956055ca020310529f",
          "md5": "1babe6cab45a8b8c1d7641122dcaf90b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.1.jar",
          "url": "backend-robovm-v157.1.jar",
          "size": 80635,
          "sha512": "d268a5bcafa9e8de80b6ca6a5937d60567dda989fd3d84a42d469c1a6e6cd3c190c6359f45d636066a1f5d8a8c76d95a2ee24dd7ad4b70958ddcc52223fec10b",
          "sha256": "6725bdcef0bc4605e0119377d143413fa4b05d7b16d9fbf61c36a4781f8735d4",
          "sha1": "25a5671eb00ff56dfc04b6956055ca020310529f",
          "md5": "1babe6cab45a8b8c1d7641122dcaf90b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v157.1-sources.jar",
          "url": "backend-robovm-v157.1-sources.jar",
          "size": 45828,
          "sha512": "54a7761747e778f8c0c038efe138e360fc35c1ad51d9dfad4cba11e8f76d332055c9686e958c0f0f438a86ec6fd01918c1e3496654084d40c11598fb93807b09",
          "sha256": "5dd040a1f8bfeb5603561099a249e98483fc6fc607a9f2a11b3c98499a50749d",
          "sha1": "6524574478265630d18c31b530bf642efaf734b1",
          "md5": "b83211e1fe9f77d86e04a98ffb9d5615"
        }
      ]
    }
  ]
}
