{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v157.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.3.jar",
          "url": "backend-robovm-v157.3.jar",
          "size": 80635,
          "sha512": "ae607d7a8c960075778d1844c7f7bd43d22fb634532ed60e776704a0ade21631bae85c5bd93f7b4a225cc807c59ae0769e67aa80f572216d463b2c1d75f49d7f",
          "sha256": "d025efb0214c8908d0e38708043b9bd9b3b45187ffa7c26314fe549519f2b139",
          "sha1": "ceccddc3dc0584c94c78c3af77f6e66a8e6959e5",
          "md5": "737cff43c2cb219ef74bfc2d40486719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.3.jar",
          "url": "backend-robovm-v157.3.jar",
          "size": 80635,
          "sha512": "ae607d7a8c960075778d1844c7f7bd43d22fb634532ed60e776704a0ade21631bae85c5bd93f7b4a225cc807c59ae0769e67aa80f572216d463b2c1d75f49d7f",
          "sha256": "d025efb0214c8908d0e38708043b9bd9b3b45187ffa7c26314fe549519f2b139",
          "sha1": "ceccddc3dc0584c94c78c3af77f6e66a8e6959e5",
          "md5": "737cff43c2cb219ef74bfc2d40486719"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v157.3-sources.jar",
          "url": "backend-robovm-v157.3-sources.jar",
          "size": 45828,
          "sha512": "3eef2562bdf03570c438eced30cd995c11548fbfeba75b52ea1c06fa22b5aec019c2f22eb3408286ec13681de01312cbf8d75a2385f477f447fc3708500a31c9",
          "sha256": "b1f6f62fff6c113fdde4d98227a2420f840a6e5cbd022be7d4a29af99e858415",
          "sha1": "e8efce46c8e73e1c5dc4ed702324c3eae883083f",
          "md5": "41807d2e91ccf396a248198caae06e7b"
        }
      ]
    }
  ]
}
