{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v157.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.2.jar",
          "url": "backend-robovm-v157.2.jar",
          "size": 80635,
          "sha512": "0a63f80e56a58c8c32dd1dc04aa97defc183fa97cedf75968ecbd381a9b9218735b9a07c4239f5325dca251293cd111c474eafffd184ad3bd3a9ab4a08132e15",
          "sha256": "4538e7f4c9bb429083e448458c0e2d1d020eba3e9c362e216ddde5089edda88d",
          "sha1": "460a6414a3ee0f9a02ed353f736fc7c3c8c490fe",
          "md5": "632be5a9c1b65a862bdbd9057751c2e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.2.jar",
          "url": "backend-robovm-v157.2.jar",
          "size": 80635,
          "sha512": "0a63f80e56a58c8c32dd1dc04aa97defc183fa97cedf75968ecbd381a9b9218735b9a07c4239f5325dca251293cd111c474eafffd184ad3bd3a9ab4a08132e15",
          "sha256": "4538e7f4c9bb429083e448458c0e2d1d020eba3e9c362e216ddde5089edda88d",
          "sha1": "460a6414a3ee0f9a02ed353f736fc7c3c8c490fe",
          "md5": "632be5a9c1b65a862bdbd9057751c2e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v157.2-sources.jar",
          "url": "backend-robovm-v157.2-sources.jar",
          "size": 45828,
          "sha512": "cf6f5a6b914ae06ee67d19516c3ab746726c117932d05e477b6146e67d9d265ca5cf4327d940318d1d9b6a0c15401c564f5a2f83ca69bc7bd9c60a17b9d6df5c",
          "sha256": "c838bed5f1745bf4515ef933a612a4515daf490229fc56048f0708ebaa61a33b",
          "sha1": "e4b61d4c6320cf090b10074a6fdfafebf52b4052",
          "md5": "66ac3876535cda19561e71bf847bbb93"
        }
      ]
    }
  ]
}
