{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v157.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.4.jar",
          "url": "backend-robovm-v157.4.jar",
          "size": 80635,
          "sha512": "c768e3e5db1b2f8412dd0c1dd1ca14e1a29c6536cf28353844dc600d96fbe3547117270b4a37b5cc2a0a325c98ed1c0ae91ea065abb5c75d16a7627e3e37a938",
          "sha256": "4490e15678894b7a1e0a6c1279a0806833fedbb8b6753aec816b602065d1ce50",
          "sha1": "b801894729c930ba22b0647cad3cd07de73aaa36",
          "md5": "1e6efe0438db950aaba8389b1edc177b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.24"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.24"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v157.4.jar",
          "url": "backend-robovm-v157.4.jar",
          "size": 80635,
          "sha512": "c768e3e5db1b2f8412dd0c1dd1ca14e1a29c6536cf28353844dc600d96fbe3547117270b4a37b5cc2a0a325c98ed1c0ae91ea065abb5c75d16a7627e3e37a938",
          "sha256": "4490e15678894b7a1e0a6c1279a0806833fedbb8b6753aec816b602065d1ce50",
          "sha1": "b801894729c930ba22b0647cad3cd07de73aaa36",
          "md5": "1e6efe0438db950aaba8389b1edc177b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v157.4-sources.jar",
          "url": "backend-robovm-v157.4-sources.jar",
          "size": 45828,
          "sha512": "579e21300200e053038751c67cfe02361b5b482f8db1db9beff5552ac7b693911d8f9efc597765193aaff9555b983c791b89c635301b081e20b1984b0a7bf330",
          "sha256": "2ad8d6591824daed18ff53e36bd532b629dc26c597ca28c1a7df132831ff2bcc",
          "sha1": "7f963ca826f2e6a44e3ca3ae7bdcc5e50ddcddb4",
          "md5": "5858883ab7be18e2e9584745d5d50678"
        }
      ]
    }
  ]
}
