{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v156.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v156.2.jar",
          "url": "backend-sdl-v156.2.jar",
          "size": 3020500,
          "sha512": "d9c484747efdb0ad96b5a03e85b8d257ff828e2f3d2c4ae55d976776d4a8480bb2d3f9a818498df0f4dce06a3fdbbacaad46c4bdff627c36a17f77c177b8d733",
          "sha256": "4049c7dbee52bc75b46491767e0b1136e99f7627fe975250d6ef065b9219c174",
          "sha1": "5f3ab6fdfa66eef0d23c187decfa11c0fd6dc198",
          "md5": "0772f34bac19cc8343426aab88307ff5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.2.jar",
          "url": "backend-sdl-v156.2.jar",
          "size": 3020500,
          "sha512": "d9c484747efdb0ad96b5a03e85b8d257ff828e2f3d2c4ae55d976776d4a8480bb2d3f9a818498df0f4dce06a3fdbbacaad46c4bdff627c36a17f77c177b8d733",
          "sha256": "4049c7dbee52bc75b46491767e0b1136e99f7627fe975250d6ef065b9219c174",
          "sha1": "5f3ab6fdfa66eef0d23c187decfa11c0fd6dc198",
          "md5": "0772f34bac19cc8343426aab88307ff5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v156.2-sources.jar",
          "url": "backend-sdl-v156.2-sources.jar",
          "size": 3001408,
          "sha512": "8978521dfbbc87a01d15756a0cf7caf085a8cde61adffb5bcc870db6e18736b17d23ec1da19c29087b02008ca2ba5f73fce38017938ee55981d427df7db79cfa",
          "sha256": "4549bfa413fc8bf92611c05f482fa898436539bd3e60a311f583623f36dc42bc",
          "sha1": "8522b58331ca003aca3ce46dfbaed2d910f87924",
          "md5": "d13d3c910f345a226d480d6b4757b442"
        }
      ]
    }
  ]
}
