{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "rhino",
    "version": "e74ac129d2bff72c1deb536d7d99a0dbb7046d2e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rhino-e74ac129d2bff72c1deb536d7d99a0dbb7046d2e.jar",
          "url": "rhino-e74ac129d2bff72c1deb536d7d99a0dbb7046d2e.jar",
          "size": 938690,
          "sha512": "30986d027b67269563293fcda481548cd65e2b5f733ff58a239de514ddaf22ab1ee8bdef1c035d3c2c5dbd134e11bcfba1a7732f2e5823a4e4c1c1dd84459ce4",
          "sha256": "7607af1671b6595f5a40cc1bcca92b7fbb2dbd4ffbcde702bf8b4170a94d27b5",
          "sha1": "afcfd1bb3d3625cd3e3d5fa6b4f39af5737b8dee",
          "md5": "012b0df85b6018f8190737e82cdc77b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rhino-e74ac129d2bff72c1deb536d7d99a0dbb7046d2e.jar",
          "url": "rhino-e74ac129d2bff72c1deb536d7d99a0dbb7046d2e.jar",
          "size": 938690,
          "sha512": "30986d027b67269563293fcda481548cd65e2b5f733ff58a239de514ddaf22ab1ee8bdef1c035d3c2c5dbd134e11bcfba1a7732f2e5823a4e4c1c1dd84459ce4",
          "sha256": "7607af1671b6595f5a40cc1bcca92b7fbb2dbd4ffbcde702bf8b4170a94d27b5",
          "sha1": "afcfd1bb3d3625cd3e3d5fa6b4f39af5737b8dee",
          "md5": "012b0df85b6018f8190737e82cdc77b4"
        }
      ]
    }
  ]
}
