{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives",
    "version": "v160.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-v160.5.jar",
          "url": "natives-v160.5.jar",
          "size": 261,
          "sha512": "9e99817a3b3ca208f88e5aa3f78099fbcb13704c13e829eec7c17f730fb449dcceb0862794e22366f0c109ae3e70b11739a9939629b4967d04cc9223aad59d5d",
          "sha256": "b2f22a0bbf9ee7ec8115353e9cd886c9128ab29f1816b927d2eda691d7c4b09a",
          "sha1": "dcd363bf98584d8ba97bcb83f95ea48b89441f48",
          "md5": "df4f08049cf432921efc17a4fa41ba6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v160.5.jar",
          "url": "natives-v160.5.jar",
          "size": 261,
          "sha512": "9e99817a3b3ca208f88e5aa3f78099fbcb13704c13e829eec7c17f730fb449dcceb0862794e22366f0c109ae3e70b11739a9939629b4967d04cc9223aad59d5d",
          "sha256": "b2f22a0bbf9ee7ec8115353e9cd886c9128ab29f1816b927d2eda691d7c4b09a",
          "sha1": "dcd363bf98584d8ba97bcb83f95ea48b89441f48",
          "md5": "df4f08049cf432921efc17a4fa41ba6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v160.5-sources.jar",
          "url": "natives-v160.5-sources.jar",
          "size": 261,
          "sha512": "9e99817a3b3ca208f88e5aa3f78099fbcb13704c13e829eec7c17f730fb449dcceb0862794e22366f0c109ae3e70b11739a9939629b4967d04cc9223aad59d5d",
          "sha256": "b2f22a0bbf9ee7ec8115353e9cd886c9128ab29f1816b927d2eda691d7c4b09a",
          "sha1": "dcd363bf98584d8ba97bcb83f95ea48b89441f48",
          "md5": "df4f08049cf432921efc17a4fa41ba6f"
        }
      ]
    }
  ]
}
