{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arcnet",
    "version": "v160.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arcnet-v160.6.jar",
          "url": "arcnet-v160.6.jar",
          "size": 52962,
          "sha512": "12a3540630c67125cffc7f5af3c219149a12bcdbb200320e33cb1e3ed711991da22ce18eb5aa93db8af379e0ca216a1f4bacb7d0464e49fbca45cdbd96330996",
          "sha256": "62fe10a4a3948277d89ad19e90f4b1ff6b651a33912b457c5dfa61cd48137556",
          "sha1": "617cbe399fb3322b7e58ba79a5e9ea3434054392",
          "md5": "33fd63f761774c16332f8ef5e2448ae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v160.6.jar",
          "url": "arcnet-v160.6.jar",
          "size": 52962,
          "sha512": "12a3540630c67125cffc7f5af3c219149a12bcdbb200320e33cb1e3ed711991da22ce18eb5aa93db8af379e0ca216a1f4bacb7d0464e49fbca45cdbd96330996",
          "sha256": "62fe10a4a3948277d89ad19e90f4b1ff6b651a33912b457c5dfa61cd48137556",
          "sha1": "617cbe399fb3322b7e58ba79a5e9ea3434054392",
          "md5": "33fd63f761774c16332f8ef5e2448ae5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v160.6-sources.jar",
          "url": "arcnet-v160.6-sources.jar",
          "size": 28697,
          "sha512": "faac2f38bbe89ff6373658f6f50f86607ff394686aba22c0a128fa79429042af6c182d7fdadcafe6d69dbacfa98f4dd5111160e1dcae55e0e90d8caf3c71214b",
          "sha256": "68c4981cf62d8fe998e33fdab4956ff884a2fd387d6f4e89025300f0b5963d39",
          "sha1": "b5e4383a2f40d816d9afcd8f45871b6113ec74ad",
          "md5": "7568a69f1a54920ffb8047ad85977fef"
        }
      ]
    }
  ]
}
