{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "g3d",
    "version": "v157",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "g3d-v157.jar",
          "url": "g3d-v157.jar",
          "size": 45674,
          "sha512": "5b75be19683425b932594e8d42fcbbf58d1d8c8dc2ca6d4c4c2d14aae500f5cb846833147dcf7673f023e2ea5f6bf0b1480955c500f907b8f99ad41db326eea7",
          "sha256": "eafe46b2b86a9553124c319b0ae5c7603805801a5574d483dde092d3a6cba281",
          "sha1": "af39516d1d5c22d0a1f23bd50034e220f753dc3c",
          "md5": "1aa3be4af42000b47c5a6aece8aae168"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v157.jar",
          "url": "g3d-v157.jar",
          "size": 45674,
          "sha512": "5b75be19683425b932594e8d42fcbbf58d1d8c8dc2ca6d4c4c2d14aae500f5cb846833147dcf7673f023e2ea5f6bf0b1480955c500f907b8f99ad41db326eea7",
          "sha256": "eafe46b2b86a9553124c319b0ae5c7603805801a5574d483dde092d3a6cba281",
          "sha1": "af39516d1d5c22d0a1f23bd50034e220f753dc3c",
          "md5": "1aa3be4af42000b47c5a6aece8aae168"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v157-sources.jar",
          "url": "g3d-v157-sources.jar",
          "size": 35333,
          "sha512": "d24d43903676845ec7394d6fd20b2f810743c8570bfd75ebc43302fde4f2fc243f48136caaaedcdc4ee3d9b5ecb6a6f087098daa6ac1d3c1b93374900e179615",
          "sha256": "69f96a5b22627c28afd4eddcf384c2b2430d1698c97307a143f08cd6811c3635",
          "sha1": "d343fc14af6be4131de9169167cb7a82ecc42467",
          "md5": "7e7c77e8a704044897c6aeda803c8d8c"
        }
      ]
    }
  ]
}
