{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v160.jar",
          "url": "backend-sdl-v160.jar",
          "size": 3020033,
          "sha512": "e9bbc91b7e686cc1f01c2138fe4fcda63315d938a5a878ca5ae974a663afe2aae05ad58acb28ffd2b1035c2fb5d2cdb6bc3faf88baa04e0c5dc2e3743faef785",
          "sha256": "29ab844f69fdd3b06abeac52d0f5356c9ae7316e355d6ce9666a31e3c5e7e017",
          "sha1": "db6451b87af3230861fcf0bbafa82e5807d0c8a0",
          "md5": "5da7d955cf0d99ebb271dbd2e85d46f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v160.jar",
          "url": "backend-sdl-v160.jar",
          "size": 3020033,
          "sha512": "e9bbc91b7e686cc1f01c2138fe4fcda63315d938a5a878ca5ae974a663afe2aae05ad58acb28ffd2b1035c2fb5d2cdb6bc3faf88baa04e0c5dc2e3743faef785",
          "sha256": "29ab844f69fdd3b06abeac52d0f5356c9ae7316e355d6ce9666a31e3c5e7e017",
          "sha1": "db6451b87af3230861fcf0bbafa82e5807d0c8a0",
          "md5": "5da7d955cf0d99ebb271dbd2e85d46f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v160-sources.jar",
          "url": "backend-sdl-v160-sources.jar",
          "size": 3001313,
          "sha512": "162ba4f5df2fe0084b7515c41a4ede2e792433d06b97fd7dc658f877881847a737a61d445778e90b2e9916a7fae842155ca0849f83f3cd9fccb3024874bff104",
          "sha256": "3fae898953d1d9f151692f4ff7805b976c4702541750224a67fe5b7c9b0202a1",
          "sha1": "abe238d4e656081576f0e168acae8c493405acb3",
          "md5": "b4749c093cb04eabb19072869c023861"
        }
      ]
    }
  ]
}
