{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "filedialogs",
    "version": "v157.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "filedialogs-v157.3.jar",
          "url": "filedialogs-v157.3.jar",
          "size": 1039,
          "sha512": "56e90d02d69838481991c381dc9bedf96a1a01f7e97249b397889e740a5cbbc18e6e72da1478d440f7f78d79713575ec4036e5183f8d608db1f215beb3940cff",
          "sha256": "817c22497ea36273692ca0b0adc06cbc0bdf7c93955e23a11f6f4c1908c555dd",
          "sha1": "739f51351eacb09364e89547a7bd9dc879e1f97f",
          "md5": "fcc13b68cdfbece76b6065ca3918df6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filedialogs-v157.3.jar",
          "url": "filedialogs-v157.3.jar",
          "size": 1039,
          "sha512": "56e90d02d69838481991c381dc9bedf96a1a01f7e97249b397889e740a5cbbc18e6e72da1478d440f7f78d79713575ec4036e5183f8d608db1f215beb3940cff",
          "sha256": "817c22497ea36273692ca0b0adc06cbc0bdf7c93955e23a11f6f4c1908c555dd",
          "sha1": "739f51351eacb09364e89547a7bd9dc879e1f97f",
          "md5": "fcc13b68cdfbece76b6065ca3918df6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "filedialogs-v157.3-sources.jar",
          "url": "filedialogs-v157.3-sources.jar",
          "size": 1476,
          "sha512": "7f0f0578ef7f92bbe12c17f4ea9b92af8f29c7ba4636fe7429bbf0dc553d2cb011967775fd6cadeaa7e1f6d5824e359612448246dde27f99e5c10c873abb247f",
          "sha256": "9f7b6e45b68a7a8ce7cb919e0a22e9a75c15bed99dc5766c72d2f7cc2ec6676f",
          "sha1": "691bff663d6fa2ae6f5027a4a6f2122612f16db1",
          "md5": "96989a4a61a95ae94d80366f52b993e2"
        }
      ]
    }
  ]
}
