{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.26"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.26"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.26"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v160.jar",
          "url": "backend-robovm-v160.jar",
          "size": 87108,
          "sha512": "caad8d96e96908f0a1c96a266049a1bb9599421e4733e3b0bc9f1318beed41819095ee3b0777b3f128f6c4c14a7e07ea64fe1a458f86a27db25ce678f0a889bb",
          "sha256": "0ad03d538cafad224ad4f40be8cf364a9b8ccddfd1110c79ee56fe25a6c4a9f3",
          "sha1": "6b57d709cba2031c646e880f3cad58820193057c",
          "md5": "29741732e05efd3add3fd58de953c981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.26"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.26"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.26"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v160.jar",
          "url": "backend-robovm-v160.jar",
          "size": 87108,
          "sha512": "caad8d96e96908f0a1c96a266049a1bb9599421e4733e3b0bc9f1318beed41819095ee3b0777b3f128f6c4c14a7e07ea64fe1a458f86a27db25ce678f0a889bb",
          "sha256": "0ad03d538cafad224ad4f40be8cf364a9b8ccddfd1110c79ee56fe25a6c4a9f3",
          "sha1": "6b57d709cba2031c646e880f3cad58820193057c",
          "md5": "29741732e05efd3add3fd58de953c981"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v160-sources.jar",
          "url": "backend-robovm-v160-sources.jar",
          "size": 47881,
          "sha512": "87b986579c91381383389747124ce83d436852cdb45a7fbb9b688e18cb8426b9aeff4f4baeae165e65be8f7cd234b69cf214625bdc6b27191b9cc467de95db4e",
          "sha256": "b232dd78c7891c9a7773e03bcfebebce70a0a2f7845906efadab270b7256fc50",
          "sha1": "90c180bbf4e142f430e02fa1f1aea02e92e380bc",
          "md5": "26c43be1679710a1829bf79c634cbf66"
        }
      ]
    }
  ]
}
