{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "server",
    "version": "v159.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "server-v159.2.jar",
          "url": "server-v159.2.jar",
          "size": 38847,
          "sha512": "414909c0a1b6928589cc4087390778e4d085d96a88f63ab2975571c0bd9d1c2ad44d03aba8259cf45bd4e57c141dbe342f4492bdcf7aa8bf48061136675957ba",
          "sha256": "73da9a6c64b834a0a8d97a4c64090cff5cf34175fd03e909d1df147553a5b2c9",
          "sha1": "6a6d9ef5c32a4f332509907cfcf14d807c8595d8",
          "md5": "a7f12e3953feb940d39a6cab63917b99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v159.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "backend-headless",
          "version": {
            "requires": "v159.2"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "server-v159.2.jar",
          "url": "server-v159.2.jar",
          "size": 38847,
          "sha512": "414909c0a1b6928589cc4087390778e4d085d96a88f63ab2975571c0bd9d1c2ad44d03aba8259cf45bd4e57c141dbe342f4492bdcf7aa8bf48061136675957ba",
          "sha256": "73da9a6c64b834a0a8d97a4c64090cff5cf34175fd03e909d1df147553a5b2c9",
          "sha1": "6a6d9ef5c32a4f332509907cfcf14d807c8595d8",
          "md5": "a7f12e3953feb940d39a6cab63917b99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "server-v159.2-sources.jar",
          "url": "server-v159.2-sources.jar",
          "size": 15024,
          "sha512": "42097825525a3845d1e05fda49dcfc75abf89d58a812a29d8aba95c1db144515c86f53e41af42f2425558da1f9a6dfba37c1fb1aea5e5f693a271ab3cbac07a6",
          "sha256": "e6cae25305421c00399210c2637f44a5d1cde81796f0a7306ef70d93b75b0f57",
          "sha1": "d4a04e14082da6f6afe431240d58b4763db57630",
          "md5": "4de024ead221ec5b333fc93e75d5ea85"
        }
      ]
    }
  ]
}
