{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v159.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "e74ac129d2bff72c1deb536d7d99a0dbb7046d2e"
          }
        }
      ],
      "files": [
        {
          "name": "core-v159.5.jar",
          "url": "core-v159.5.jar",
          "size": 5901239,
          "sha512": "4341c8774149b8247acf9ae588b618288572fb49b4796d6d0f4db10e1f143fa84db81b4f5ce3a4e47d7d0b72be09355042677da17af5e54fad88dadf0b26b979",
          "sha256": "7be829b800aa6c50d7cbd23c989a4c338b8ff12525ecffa91ec86ece69a3ec97",
          "sha1": "4a87f6006312aee85009f7bd9ec301a51b1488fc",
          "md5": "566dab31bef826ad852ed1dc1e35c42c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.yawk.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v159.5"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "e74ac129d2bff72c1deb536d7d99a0dbb7046d2e"
          }
        }
      ],
      "files": [
        {
          "name": "core-v159.5.jar",
          "url": "core-v159.5.jar",
          "size": 5901239,
          "sha512": "4341c8774149b8247acf9ae588b618288572fb49b4796d6d0f4db10e1f143fa84db81b4f5ce3a4e47d7d0b72be09355042677da17af5e54fad88dadf0b26b979",
          "sha256": "7be829b800aa6c50d7cbd23c989a4c338b8ff12525ecffa91ec86ece69a3ec97",
          "sha1": "4a87f6006312aee85009f7bd9ec301a51b1488fc",
          "md5": "566dab31bef826ad852ed1dc1e35c42c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v159.5-sources.jar",
          "url": "core-v159.5-sources.jar",
          "size": 1595785,
          "sha512": "9c5ea9d1158584ccea7f34e1db316289fdf86630fddbbaf795ef4eb7d8afa209280d67d501159b989a82534ddea9545cdeea1f2394a25785b9a70afce1d488bd",
          "sha256": "5838645d416a9e2785fcb51f9e26939ee75592ddd5b6e3a347bf25f2addbdc14",
          "sha1": "9200a5bead0b11796816ba6ae9d3221ca232a82d",
          "md5": "62b9f7ae9612753c791407779e906f7e"
        }
      ]
    }
  ]
}
